title: Site

pages:
     template: documentation

files: false

fields:
     title:
          label: Title
          type:  text
          width: 2/3
          required: true

     version:
          label: Version
          type:  text
          width: 1/3
          required: true
